"""add phone address dp to users

Revision ID: 9c63dd6192ec
Revises: 3606621bec6d
Create Date: 2026-01-14 17:14:35.206011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c63dd6192ec'
down_revision: Union[str, Sequence[str], None] = '3606621bec6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('dp', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'dp')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
