"""make all columns mandatory

Revision ID: ae618d227018
Revises: 24798d24d89b
Create Date: 2026-01-15 17:26:34.136013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae618d227018'
down_revision: Union[str, Sequence[str], None] = '24798d24d89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(10),
        nullable=False
    )
    
    op.alter_column('users', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'dp',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column(
          "users","updated_at",
          existing_type=sa.DateTime(),
          nullable=False,
          server_default=sa.text("CURRENT_TIMESTAMP"),)
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'dp',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
