"""Alembic context stubs"""
from typing import Any, ContextManager, Optional

class Config:
    config_file_name: Optional[str]
    config_ini_section: str
    def get_main_option(self, name: str) -> Optional[str]: ...
    def get_section(self, name: str, defaults: Any = None) -> Any: ...

config: Config
def configure(**kwargs: Any) -> None: ...
def begin_transaction() -> ContextManager[None]: ...
def run_migrations() -> None: ...
def is_offline_mode() -> bool: ...
def execute(sql: Any, execution_options: Optional[Any] = None) -> Any: ...
